apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase
  template:
    metadata:
      labels:
        app: supabase
    spec:
      containers:
      - name: supabase
        image: supabase/postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "your-supabase-password"
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-service
spec:
  selector:
    app: supabase
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
