apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-ai
  template:
    metadata:
      labels:
        app: master-ai
    spec:
      initContainers:
      - name: wait-for-supabase
        image: busybox
        command: ['sh', '-c', 'until nc -z supabase-service 8000; do echo waiting for supabase; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: master-ai
        image: master-ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SUPABASE_URL
          value: "http://supabase-service:8000"
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-anon-key
        resources:
          limits:
            nvidia.com/gpu: 1  # Request 1 GPU
        volumeMounts:
        - name: master-ai-storage
          mountPath: /app/models
      volumes:
      - name: master-ai-storage
        persistentVolumeClaim:
          claimName: master-ai-data
---
apiVersion: v1
kind: Service
metadata:
  name: master-ai-service
spec:
  selector:
    app: master-ai
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080









































































































































































































































