apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
      - name: openwebui
        image: openwebui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_API_BASE_URL
          value: "http://ollama-service:11434"
        volumeMounts:
        - name: openwebui-storage
          mountPath: /app/data
      volumes:
      - name: openwebui-storage
        persistentVolumeClaim:
          claimName: openwebui-data
---
apiVersion: v1
kind: Service
metadata:
  name: openwebui-service
spec:
  selector:
    app: openwebui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080












































































































