apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-ai
  template:
    metadata:
      labels:
        app: master-ai
    spec:
      containers:
      - name: master-ai
        image: master:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SUPABASE_HOST
          value: "supabase-service"
---
apiVersion: v1
kind: Service
metadata:
  name: master-ai-service
spec:
  selector:
    app: master-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
