apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ai-70b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-ai-70b
  template:
    metadata:
      labels:
        app: worker-ai-70b
    spec:
      containers:
      - name: worker-ai-70b
        image: worker:latest
        env:
        - name: MODEL_SIZE
          value: "70B"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
