apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ai-34b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-ai-34b
  template:
    metadata:
      labels:
        app: worker-ai-34b
    spec:
      containers:
      - name: worker-ai-34b
        image: worker:latest
        imagePullPolicy: Never
        env:
        - name: MODEL_SIZE
          value: "34B"
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
