apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agentk
  template:
    metadata:
      labels:
        app: agentk
    spec:
      containers:
      - name: agentk
        image: your-docker-registry/agentk:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
